-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 22:16:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`cabinets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`cabinets` (
  `idcab` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`idcab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`doctors` (
  `iddoc` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `specialty` VARCHAR(100) NOT NULL,
  `cabinet` INT NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`iddoc`),
  INDEX `cab_idx` (`cabinet` ASC) VISIBLE,
  CONSTRAINT `cab_to_doc`
    FOREIGN KEY (`cabinet`)
    REFERENCES `hospital`.`cabinets` (`idcab`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`patients` (
  `idpat` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `bod` DATE NULL,
  `phone_number` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `doc_id` INT NOT NULL,
  PRIMARY KEY (`idpat`),
  INDEX `doc_idx` (`doc_id` ASC) VISIBLE,
  CONSTRAINT `doc_to_pat`
    FOREIGN KEY (`doc_id`)
    REFERENCES `hospital`.`doctors` (`iddoc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`diagnoses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`diagnoses` (
  `iddiag` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddiag`),
  INDEX `pat_idx` (`patient_id` ASC) VISIBLE,
  INDEX `doc_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `pat_to_diag`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital`.`patients` (`idpat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doc_to_diag`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospital`.`doctors` (`iddoc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`recipes` (
  `idrec` INT NOT NULL AUTO_INCREMENT,
  `diagnos_id` INT NOT NULL,
  `medcines` SET('aрбидол', 'азитромицин') NULL,
  `total_cost` VARCHAR(45) NULL,
  PRIMARY KEY (`idrec`),
  INDEX `pat_idx` (`diagnos_id` ASC) VISIBLE,
  CONSTRAINT `pat_to_rec`
    FOREIGN KEY (`diagnos_id`)
    REFERENCES `hospital`.`diagnoses` (`iddiag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
